export const GET_INVOICES_REQUEST = 'GET_INVOICES_REQUEST';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICES_FAILURE = 'GET_INVOICES_FAILURE';

export const INVOICE_STATUS_REQUEST = 'INVOICE_STATUS_REQUEST';
export const INVOICE_STATUS_SUCCESS = 'INVOICE_STATUS_SUCCESS';
export const INVOICE_STATUS_FAILURE = 'INVOICE_STATUS_FAILURE';
